@startuml
abstract class com.mygdx.platventure.elements.Element {
# Vector2 position
# Body body
# BodyDef bodyDef
# Texture texture
# float largeur
# float hauteur
+ {abstract}void setBodyDef()
+ {abstract}void setFixture()
+ void createBody(World)
+ void setPosition(Vector2)
+ void setBody(Body)
+ Vector2 getPosition()
+ Body getBody()
+ {abstract}void dispose()
+ {abstract}Texture getTexture()
+ {abstract}float getLargeur()
+ {abstract}float getHauteur()
}
class com.mygdx.platventure.Monde {
- World monde
- ArrayList<Element> elementsDuMonde
- Personnage personnage
- EcouteurCollision collisionJoueur
- Niveau niveau
- Timer timer
+ int score
- int numeroNiveauActuel
- int[] tempsRestant
- boolean persoVientDeSpawn
- boolean aGagne
- boolean jeuEstEnPause
- GestionnaireSons gestionnaireSons
- boolean isAlerted
- Timer timerAlert
- boolean estAuNiveau3
+ void creerMonde(int)
+ void creerElementDuMonde(char[][],int,int,int)
+ World getMonde()
+ Personnage getPersonnage()
+ void update()
+ void dispose()
+ Niveau getNiveau()
+ boolean isPersoVientDeSpawn()
+ void setPersoVientDeSpawn(boolean)
+ int getScore()
+ int[] getTempsRestant()
+ void mortDuJoueur()
+ boolean isaGagne()
+ boolean isJeuEstEnPause()
+ ArrayList<Element> getElementsDuMonde()
+ void passerAuNiveauSuivant()
+ void ajouterScore()
+ boolean isEstAuNiveau3()
}
class com.mygdx.platventure.elements.Sortie {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.ecouteurs.EcouteurEcranJeu {
- Vector2 force
- boolean skipNiveau
- boolean addScore
- boolean debugMode
+ boolean keyDown(int)
+ boolean keyUp(int)
+ boolean keyTyped(char)
+ boolean touchDown(int,int,int,int)
+ boolean touchUp(int,int,int,int)
+ boolean touchDragged(int,int,int)
+ boolean mouseMoved(int,int)
+ boolean scrolled(float,float)
+ Vector2 getForce()
+ boolean isSkipNiveau()
+ void setSkipNiveau(boolean)
+ boolean isAddScore()
+ void setAddScore(boolean)
+ boolean isDebugMode()
}
abstract class com.mygdx.platventure.elements.gemmes.Gemmes {
- CircleShape forme
- Animation animation
+ void setBodyDef()
+ void setFixture()
+ {abstract}int getValeurGemme()
+ float getLargeur()
+ float getHauteur()
+ Animation getAnimation()
# void animationGemmes()
}
class com.mygdx.platventure.elements.gemmes.GemmeRouge {
+ int getValeurGemme()
+ void dispose()
+ Texture getTexture()
}
class com.mygdx.platventure.elements.plateformes.PlateformeGauche {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.elements.plateformes.PlateformeMilieu {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.elements.gemmes.GemmeJaune {
+ int getValeurGemme()
+ void dispose()
+ Texture getTexture()
}
class com.mygdx.platventure.elements.Personnage {
- PolygonShape forme
- CircleShape cercle
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void appliquerForce(Vector2)
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
+ void setTexture(Texture)
}
class com.mygdx.platventure.elements.Eau {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.PlatVenture {
- SpriteBatch batch
+ void create()
+ void dispose()
+ SpriteBatch getBatch()
}
class com.mygdx.platventure.elements.Brique {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.Niveau {
- int largeur
- int hauteur
- int temps
- String imageDeFond
- char[][] tabNiveau
+ int getLargeur()
+ int getHauteur()
+ char[][] getTabNiveau()
+ int getTemps()
+ void dispose()
}
class com.mygdx.platventure.ecrans.EcranTitre {
~ PlatVenture platVenture
- Texture texture
+ void show()
+ void render(float)
}
class com.mygdx.platventure.elements.plateformes.PlateformeDroite {
- PolygonShape forme
- float densite
- float restitution
- float friction
+ void setBodyDef()
+ void setFixture()
+ void dispose()
+ Texture getTexture()
+ float getLargeur()
+ float getHauteur()
}
class com.mygdx.platventure.ecrans.EcranJeu {
- PlatVenture platVenture
- Texture texture
- OrthographicCamera camera
- FitViewport vp
- Monde monde
- Box2DDebugRenderer debug
- EcouteurEcranJeu mouvementJoueur
- BitmapFont font
- OrthographicCamera cameraTexte
- int cptChangementAnimation
- int numSpriteGemmes
+ void show()
+ void render(float)
+ void resize(int,int)
+ void positionnerCameraPersonnage()
- void defineTextFont()
}
class com.mygdx.platventure.GestionnaireSons {
- Sound sonWin
- Sound sonGemmes
- Sound sonAlert
- Sound sonCollision
- Sound sonDefaite
- Sound sonPlouf
+ void jouerSonWin()
+ void jouerSonGemmes()
+ void jouerSonAlert()
+ void jouerSonCollision()
+ void jouerSonDefaite()
+ void jouerSonPlouf()
}
class com.mygdx.platventure.ecouteurs.EcouteurCollision {
- boolean collisionEntrePersoEtGemmes
- boolean collisionEntrePersoEtEau
- boolean collisionEntrePersoEtSortie
- boolean collisionRapideEntrePersoEtBriqueEtPlateformes
- Body gemmes
+ void beginContact(Contact)
+ void endContact(Contact)
+ void preSolve(Contact,Manifold)
+ void postSolve(Contact,ContactImpulse)
+ boolean isCollisionEntrePersoEtGemmes()
+ boolean isCollisionEntrePersoEtEau()
+ boolean isCollisionEntrePersoEtSortie()
+ boolean isCollisionRapideEntrePersoEtBriqueEtPlateformes()
+ Body getGemmes()
+ void setCollisionEntrePersoEtGemmes(boolean)
+ void setCollisionEntrePersoEtEau(boolean)
+ void setCollisionEntrePersoEtSortie(boolean)
+ void setCollisionRapideEntrePersoEtBriqueEtPlateformes(boolean)
+ void dispose()
}


com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.Sortie
com.badlogic.gdx.InputProcessor <|.. com.mygdx.platventure.ecouteurs.EcouteurEcranJeu
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.gemmes.Gemmes
com.mygdx.platventure.elements.gemmes.Gemmes <|-- com.mygdx.platventure.elements.gemmes.GemmeRouge
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.plateformes.PlateformeGauche
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.plateformes.PlateformeMilieu
com.mygdx.platventure.elements.gemmes.Gemmes <|-- com.mygdx.platventure.elements.gemmes.GemmeJaune
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.Personnage
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.Eau
com.badlogic.gdx.Game <|-- com.mygdx.platventure.PlatVenture
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.Brique
com.badlogic.gdx.ScreenAdapter <|-- com.mygdx.platventure.ecrans.EcranTitre
com.mygdx.platventure.elements.Element <|-- com.mygdx.platventure.elements.plateformes.PlateformeDroite
com.badlogic.gdx.ScreenAdapter <|-- com.mygdx.platventure.ecrans.EcranJeu
com.badlogic.gdx.physics.box2d.ContactListener <|.. com.mygdx.platventure.ecouteurs.EcouteurCollision
@enduml